"""empty message

Revision ID: 4d168de178d1
Revises: f282e6c5761
Create Date: 2014-08-07 04:02:20.778000

"""

# revision identifiers, used by Alembic.
revision = '4d168de178d1'
down_revision = 'f282e6c5761'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
