"""empty message

Revision ID: 4dd5686ed4db
Revises: None
Create Date: 2014-09-28 13:34:07.078000

"""

# revision identifiers, used by Alembic.
revision = '4dd5686ed4db'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspire', sa.Column('photo', sa.Text(length=255), nullable=True))
    op.add_column('process', sa.Column('photo', sa.Text(length=255), nullable=True))
    op.add_column('user', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.drop_column('user', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'user_id')
    op.drop_column('process', 'photo')
    op.drop_column('inspire', 'photo')
    ### end Alembic commands ###
